// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
  description, completed
) VALUES (
  ?, ?
)
RETURNING id, description, completed
`

type CreateTodoParams struct {
	Description string
	Completed   bool
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Description, arg.Completed)
	var i Todo
	err := row.Scan(&i.ID, &i.Description, &i.Completed)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const listTodos = `-- name: ListTodos :many



SELECT id, description, completed FROM todos
ORDER BY description ASC
`

// --------------
// each query needs a name and a type (:one, :many, :exec),
// sqlc turns it into a method on db.Queries (run make sqlc after changes)
// --------------
func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(&i.ID, &i.Description, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodos = `-- name: SearchTodos :many
SELECT id, description, completed FROM todos
WHERE description LIKE '%' || ? || '%'
ORDER BY description ASC
`

func (q *Queries) SearchTodos(ctx context.Context, dollar_1 sql.NullString) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, searchTodos, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(&i.ID, &i.Description, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTodoCompleted = `-- name: ToggleTodoCompleted :one
UPDATE todos
set completed = NOT completed
WHERE id = ?
RETURNING id, description, completed
`

func (q *Queries) ToggleTodoCompleted(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, toggleTodoCompleted, id)
	var i Todo
	err := row.Scan(&i.ID, &i.Description, &i.Completed)
	return i, err
}

const updateTodoDescription = `-- name: UpdateTodoDescription :one
UPDATE todos
set description = ?
WHERE id = ?
RETURNING id, description, completed
`

type UpdateTodoDescriptionParams struct {
	Description string
	ID          int64
}

func (q *Queries) UpdateTodoDescription(ctx context.Context, arg UpdateTodoDescriptionParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoDescription, arg.Description, arg.ID)
	var i Todo
	err := row.Scan(&i.ID, &i.Description, &i.Completed)
	return i, err
}
